# Conda environment file for Java Code Classification Tool
# Python 3.12.3 - Tested and verified environment
# 
# To create the environment:
# conda env create -f environment.yml
# conda activate java-classifier

name: java-classifier
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python version - exact match
  - python=3.12.3

  # Core ML dependencies
  - torch=2.5.1
  - pytorch-cuda=12.1  # For CUDA support
  - pytorch-mutex=1.0=cuda
  - pandas=2.2.3
  - numpy=1.26.4
  - scikit-learn=1.6.1
  - joblib=1.4.2

  # Machine Learning models
  - xgboost=3.0.2
  - catboost=1.2.7
  - lightgbm=4.6.0

  # NLP and transformers
  - transformers=4.51.3
  - huggingface_hub=0.31.2
  - tokenizers=0.21.0

  # Additional ML libraries
  - scikit-image=0.25.0
  - imbalanced-learn=0.13.0
  - scipy=1.12.0
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - plotly=6.1.2

  # Utilities
  - tqdm=4.67.1
  - psutil=5.9.0
  - requests=2.32.3
  - pyyaml=6.0.2
  - pillow=11.1.0
  - packaging=24.2

  # File handling and parsing
  - beautifulsoup4=4.12.3
  - charset-normalizer=3.3.2
  - urllib3=2.3.0
  - certifi=2025.6.15

  # Image processing
  - imageio=2.37.0
  - tifffile=2025.2.18

  # Additional scientific libraries
  - statsmodels=0.14.4
  - networkx=3.4.2

  # GUI dependencies (tkinter is built-in with Python)
  # Optional: Jupyter for development
  - jupyterlab=4.3.4
  - notebook=7.3.2
  - ipykernel=6.29.5

  # Additional CUDA libraries (if using GPU)
  - cuda-cudart=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-runtime=12.1.0

  # Dependencies via pip (not available in conda)
  - pip
  - pip:
      - huggingface-hub==0.31.1  # Latest version
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - sympy==1.13.1
      - timm==1.0.15  # For additional model support
      - fsspec==2025.3.2  # File system utilities